# Generated by Django 4.0.1 on 2023-05-30 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Material', '0001_initial'),
        ('Cliente', '0001_initial'),
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('SK_ESTADO_PROYECTO', models.AutoField(primary_key=True, serialize=False)),
                ('ST_ESTADO_PROYECTO', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'estado_proyecto',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('SK_PROYECTO', models.AutoField(primary_key=True, serialize=False)),
                ('ST_DIRECCION_PROYECTO', models.CharField(max_length=120)),
                ('NM_LATITUD_PROYECTO', models.FloatField()),
                ('NM_LONGITUD_PROYECTO', models.FloatField()),
                ('ST_DESCRIPCION_PROYECTO', models.CharField(max_length=120)),
                ('FC_INGRESO_PROYECTO', models.DateTimeField(default=django.utils.timezone.now)),
                ('SK_CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('SK_ESTADO_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.estadoproyecto')),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('SK_TIPO_SERVICIO', models.AutoField(primary_key=True, serialize=False)),
                ('ST_TIPO_SERVICIO', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'tipo_servicio',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('SK_TRANSPORTE', models.AutoField(primary_key=True, serialize=False)),
                ('NM_VOLUMEN', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ST_UNIDAD_TRANSPORTE', models.CharField(choices=[('LITRO', 'Litro'), ('MILILITRO', 'Mililitro'), ('METRO_CUBICO', 'Metro cúbico'), ('PULGADA_CUBICA', 'Pulgada cúbica'), ('GALON', 'Galón')], max_length=50)),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
            options={
                'db_table': 'transporte',
            },
        ),
        migrations.CreateModel(
            name='SenializacionVial',
            fields=[
                ('SK_SENIALIZACION_VIAL', models.AutoField(primary_key=True, serialize=False)),
                ('ST_ESPECIFICACION_VIAL', models.CharField(max_length=120)),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
            options={
                'db_table': 'senializacion_vial',
            },
        ),
        migrations.CreateModel(
            name='RentaEquipo',
            fields=[
                ('SK_RENTA_EQUIPO', models.AutoField(primary_key=True, serialize=False)),
                ('FC_SALIDA_EQUIPO', models.DateTimeField()),
                ('FC_ENTRADA_EQUIPO', models.DateTimeField()),
                ('ST_TIPO_USO', models.CharField(max_length=100)),
                ('ST_OBSERVACION_EQUIPO', models.CharField(max_length=120, null=True)),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
            options={
                'db_table': 'renta_equipo',
            },
        ),
        migrations.CreateModel(
            name='RentaDesimetro',
            fields=[
                ('SK_RENTA_DESIMETRO', models.AutoField(primary_key=True, serialize=False)),
                ('FC_SALIDA_DESIMETRO', models.DateTimeField()),
                ('FC_ENTRADA_DESIMETRO', models.DateTimeField()),
                ('ST_NOMBRE_TECNICO', models.CharField(max_length=50)),
                ('ST_OBSERVACION_DESIMETRO', models.CharField(max_length=120, null=True)),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
            options={
                'db_table': 'renta_desimetro',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='SK_TIPO_SERVICIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.tiposervicio'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='SK_USUARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LevantamientoTopografico',
            fields=[
                ('SK_LEVANTAMIENTO_TOPOGRAFICO', models.AutoField(primary_key=True, serialize=False)),
                ('NM_AREA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ST_UNIDAD_LEVANTAMIENTO', models.CharField(choices=[('METRO_CUADRADRO', 'Metro cuadrado'), ('PULGADA_CUADRADA', 'Pulgada cuadrada'), ('PIE_CUADRADO', 'Pie cuadrado'), ('HECTAREA', 'Hectárea'), ('ACRE', 'Acre')], max_length=50)),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
            options={
                'db_table': 'levantamiento_topografico',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('SK_FACTURA', models.AutoField(primary_key=True, serialize=False)),
                ('ST_FACTURA', models.FileField(upload_to='factura/')),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='EstructuraMetalica',
            fields=[
                ('SK_ESTRUCTURA_METALICA', models.AutoField(primary_key=True, serialize=False)),
                ('ST_TIPO_DOC_CONCRETO', models.CharField(choices=[('PLANO', 'Plano'), ('ESPECIFICACIONES', 'Especificaciones')], max_length=25)),
                ('ST_DOC_CONCRETO', models.FileField(upload_to='doc_vial/')),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
            options={
                'db_table': 'estructura_metalica',
            },
        ),
        migrations.CreateModel(
            name='Concreto',
            fields=[
                ('SK_CONCRETO', models.AutoField(primary_key=True, serialize=False)),
                ('ST_TIPO_DOC_CONCRETO', models.CharField(choices=[('PLANO', 'Plano'), ('ESPECIFICACIONES', 'Especificaciones')], max_length=25)),
                ('ST_DOC_CONCRETO', models.FileField(upload_to='doc_concreto/')),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
            options={
                'db_table': 'concreto',
            },
        ),
        migrations.CreateModel(
            name='AsignacionMaterial',
            fields=[
                ('SK_ASIG_MATERIAL', models.AutoField(primary_key=True, serialize=False)),
                ('ST_DESCRIPCION', models.CharField(blank=True, max_length=50, null=True)),
                ('SK_MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.material')),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
            options={
                'db_table': 'asignacion_material',
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('SK_ASIG_EQUIPO', models.AutoField(primary_key=True, serialize=False)),
                ('SK_EQUIPO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipo.equipo')),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
            options={
                'db_table': 'asignacion_equipo',
            },
        ),
        migrations.CreateModel(
            name='AsignacionEmpleado',
            fields=[
                ('SK_ASIG_EMPLEADO', models.AutoField(primary_key=True, serialize=False)),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
                ('SK_USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asignacion_empleado',
            },
        ),
        migrations.CreateModel(
            name='AsesoriaConstructiva',
            fields=[
                ('SK_ASESORIA', models.AutoField(primary_key=True, serialize=False)),
                ('NM_TIEMPO', models.IntegerField()),
                ('ST_UNIDAD_ASESORIA', models.CharField(choices=[('DIA', 'Día'), ('MES', 'Mes'), ('AÑO', 'Año')], max_length=50)),
                ('SK_PROYECTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
            options={
                'db_table': 'asesoria_constructiva',
            },
        ),
    ]
