# Generated by Django 4.1.3 on 2023-09-22 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_alter_cliente_st_doc_cliente_and_more'),
        ('Proyecto', '0002_rename_sk_proyecto_asesoriaconstructiva_fk_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='FK_CLIENTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FK_ESTADO_PROYECTO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.estadoproyecto', verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FK_TIPO_SERVICIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.tiposervicio', verbose_name='Tipo de Servicio:'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='NM_LATITUD_PROYECTO',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='NM_LONGITUD_PROYECTO',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ST_DESCRIPCION_PROYECTO',
            field=models.CharField(max_length=120, verbose_name='Descripción:'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ST_DIRECCION_PROYECTO',
            field=models.CharField(max_length=120, verbose_name='Dirección:'),
        ),
        migrations.AlterField(
            model_name='rentaequipo',
            name='ST_OBSERVACION_EQUIPO',
            field=models.CharField(max_length=120, null=True, verbose_name='Observación:'),
        ),
        migrations.AlterField(
            model_name='rentaequipo',
            name='ST_TIPO_USO',
            field=models.CharField(max_length=100, verbose_name='Tipo de uso:'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='NM_VOLUMEN',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volumen:'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='ST_UNIDAD_TRANSPORTE',
            field=models.CharField(choices=[('LITRO', 'Litro'), ('MILILITRO', 'Mililitro'), ('METRO_CUBICO', 'Metro cúbico'), ('PULGADA_CUBICA', 'Pulgada cúbica'), ('GALON', 'Galón')], max_length=50, verbose_name='Unidad de volumen:'),
        ),
    ]
