# Generated by Django 4.0.1 on 2023-09-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0003_alter_proyecto_fk_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaequipo',
            name='FC_ENTRADA_EQUIPO',
            field=models.DateTimeField(verbose_name='Fecha de entrada:'),
        ),
        migrations.AlterField(
            model_name='rentaequipo',
            name='FC_SALIDA_EQUIPO',
            field=models.DateTimeField(verbose_name='Fecha de salida:'),
        ),
    ]
