# Generated by Django 4.2.1 on 2023-09-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0004_alter_rentaequipo_fc_entrada_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoriaconstructiva',
            name='NM_TIEMPO',
            field=models.IntegerField(verbose_name='N° de tiempo:'),
        ),
        migrations.AlterField(
            model_name='asesoriaconstructiva',
            name='ST_UNIDAD_ASESORIA',
            field=models.CharField(choices=[('DIA', 'Día'), ('MES', 'Mes'), ('AÑO', 'Año')], max_length=50, verbose_name='Unidades de tiempo'),
        ),
        migrations.AlterField(
            model_name='concreto',
            name='ST_DOC_CONCRETO',
            field=models.FileField(upload_to='doc_concreto/', verbose_name='Documento:'),
        ),
        migrations.AlterField(
            model_name='concreto',
            name='ST_TIPO_DOC_CONCRETO',
            field=models.CharField(choices=[('PLANO', 'Plano'), ('ESPECIFICACIONES', 'Especificaciones')], max_length=25, verbose_name='Tipo de documento:'),
        ),
        migrations.AlterField(
            model_name='levantamientotopografico',
            name='NM_AREA',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área:'),
        ),
        migrations.AlterField(
            model_name='levantamientotopografico',
            name='ST_UNIDAD_LEVANTAMIENTO',
            field=models.CharField(choices=[('METRO_CUADRADRO', 'Metro cuadrado'), ('PULGADA_CUADRADA', 'Pulgada cuadrada'), ('PIE_CUADRADO', 'Pie cuadrado'), ('HECTAREA', 'Hectárea'), ('ACRE', 'Acre')], max_length=50, verbose_name='Unidad de medida:'),
        ),
        migrations.AlterField(
            model_name='rentadesimetro',
            name='FC_ENTRADA_DESIMETRO',
            field=models.DateTimeField(verbose_name='Fecha de entrada:'),
        ),
        migrations.AlterField(
            model_name='rentadesimetro',
            name='FC_SALIDA_DESIMETRO',
            field=models.DateTimeField(verbose_name='Fecha de salida:'),
        ),
        migrations.AlterField(
            model_name='rentadesimetro',
            name='ST_NOMBRE_TECNICO',
            field=models.CharField(max_length=50, verbose_name='Nombre del técnico:'),
        ),
        migrations.AlterField(
            model_name='rentadesimetro',
            name='ST_OBSERVACION_DESIMETRO',
            field=models.CharField(max_length=120, null=True, verbose_name='Observación:'),
        ),
    ]
