# Generated by Django 4.0.1 on 2023-09-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0005_alter_asesoriaconstructiva_nm_tiempo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoriaconstructiva',
            name='NM_TIEMPO',
            field=models.IntegerField(verbose_name='Cantidad de tiempo:'),
        ),
        migrations.AlterField(
            model_name='estructurametalica',
            name='ST_DOC_CONCRETO',
            field=models.FileField(upload_to='doc_vial/', verbose_name='Documento:'),
        ),
        migrations.AlterField(
            model_name='estructurametalica',
            name='ST_TIPO_DOC_CONCRETO',
            field=models.CharField(choices=[('PLANO', 'Plano'), ('ESPECIFICACIONES', 'Especificaciones')], max_length=25, verbose_name='Tipo de documento:'),
        ),
        migrations.AlterField(
            model_name='senializacionvial',
            name='ST_ESPECIFICACION_VIAL',
            field=models.CharField(max_length=120, verbose_name='Especificacion:'),
        ),
    ]
