# Generated by Django 4.0.1 on 2023-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_alter_usuario_fc_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='BN_ESTADO_USUARIO',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ST_DUI_USUARIO',
            field=models.CharField(error_messages={'unique': 'El DUI ingresado ya existe en el sistema. Por favor, ingrese otro DUI.'}, max_length=10, unique=True, verbose_name='DUI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ST_NIT_USUARIO',
            field=models.CharField(blank=True, error_messages={'unique': 'El NIT ingresado ya existe en el sistema. Por favor, ingrese otro NIT.'}, max_length=17, null=True, unique=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'El correo ingresado ya existe en el sistema. Por favor, ingrese otro correo.'}, max_length=254, unique=True, verbose_name='Dirección de correo electrónico'),
        ),
    ]
