# Generated by Django 4.0.1 on 2023-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0003_usuario_bn_estado_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ST_AFP_USUARIO',
            field=models.CharField(blank=True, error_messages={'unique': 'El NUP ingresado ya existe en el sistema. Por favor, ingrese otro NUP.'}, max_length=12, null=True, unique=True, verbose_name='AFP'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ST_ISSS_USUARIO',
            field=models.CharField(blank=True, error_messages={'unique': 'El N° de Afiliación ingresado ya existe en el sistema. Por favor, ingrese otro N° de Afiliación.'}, max_length=9, null=True, verbose_name='ISSS'),
        ),
    ]
