# Generated by Django 4.1.3 on 2023-09-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0005_rename_sk_usuario_documentousuario_fk_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentousuario',
            name='ST_DOC_USUARIO',
            field=models.FileField(blank=True, upload_to='doc_usuario/'),
        ),
    ]
