# Generated by Django 4.2.1 on 2023-06-03 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0002_equipo_bn_estado_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='FC_INGRESO',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de ingreso'),
        ),
    ]
