# Generated by Django 4.1.3 on 2023-06-06 23:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Equipo", "0003_equipo_fc_ingreso"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="ST_IMG_EQUIPO",
            field=models.FileField(
                default="img_equipo/default.jpg",
                upload_to="img_equipo/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Imagen del equipo",
            ),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="SK_TIPO_EQUIPO",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Equipo.tipoequipo",
                verbose_name="Tipo de Equipo",
            ),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="ST_DESCRIPCION_EQUIPO",
            field=models.CharField(max_length=120, verbose_name="Descripcion"),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="ST_NOMBRE_EQUIPO",
            field=models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
        ),
    ]
