# Generated by Django 4.1.3 on 2023-05-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='BN_ESTA_ACTIVO',
            field=models.BooleanField(default=True),
        ),
    ]
