# Generated by Django 4.0.1 on 2023-06-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_cliente_bn_esta_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='SK_USUARIO',
            new_name='FK_USUARIO',
        ),
    ]
