# Generated by Django 4.1.3 on 2023-09-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_rename_sk_usuario_cliente_fk_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ST_DOC_CLIENTE',
            field=models.CharField(error_messages={'unique': 'El documento del cliente ingresado ya existe en el sistema. Por favor, ingrese otro documento.'}, max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ST_NIT_CLIENTE',
            field=models.CharField(error_messages={'unique': 'El NIT del cliente ingresado ya existe en el sistema. Por favor, ingrese otro NIT.'}, max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ST_NOMBRE_CLIENTE',
            field=models.CharField(error_messages={'unique': 'El nombre del cliente ingresado ya existe en el sistema. Por favor, ingrese otro nombre.'}, max_length=100, unique=True),
        ),
    ]
