# Generated by Django 4.0.1 on 2023-05-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('SK_MATERIAL', models.AutoField(primary_key=True, serialize=False)),
                ('ST_NOMBRE_MATERIAL', models.CharField(max_length=60, unique=True)),
                ('ST_DESCRIPCION_MATERIAL', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'material',
            },
        ),
    ]
