# Generated by Django 4.0.1 on 2023-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0002_material_bn_estado_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='ST_DESCRIPCION_MATERIAL',
            field=models.CharField(max_length=120, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='material',
            name='ST_NOMBRE_MATERIAL',
            field=models.CharField(error_messages={'unique': 'Ya existe un material con este nombre.'}, max_length=60, unique=True, verbose_name='Nombre'),
        ),
    ]
